cmake/clang-format.cmake, resources/.clang-format.in, resources/Doxyfile.in, resources/check_format.sh, resources/format.sh
-  that allow you to format your code automatically according to the copied .clang-format.in file in resources/
- 1/ developers will have to add the macro `FORMAT_CODE` in their CMakeLists.txt.
- 2/ developers can compile their code using: `catkin_make -DFORMAT_CODE_DURING_BUILD=ON`
And their codes are going to be automatically formated.
update the .clang-format to satisfy mpi requierement
=> add a macro "format_code"

cmake/doxygen.cmake, resources/Doxyfile.in, resources/py_filter
This PR adds a dependency to doxypypy: `pip install doxypypy` 
It allows Doxygen to parse the python docstrings (Google format is the best yet),
and to use Doxygen own special commands in Python as well.
I wrote the Doxygen/Google documentation of the ci_example_python package.
=> update the doxyfile to depend on doxypypy.

CMakeLists.txt, cmake/clang-format.cmake, cmake/doxygen.cmake, cmake/python.cmake, resources/Doxyfile.in, resources/package_paths.cmake.in, scripts/yaml2oneline
The `mpi_cmake_modules_SOURCE_DIR` variable needs to be set inside
python.cmake, otherwise the variable will be empty when using isolated
build.
The same probably needs to be done in some other files as well.
=> Set package path inside python.cmake

cmake/XenomaiConfig.cmake, cmake/global_calls.cmake, cmake/os_detection.cmake, cmake/setup_xenomai.cmake
mpi_cmake_modules setup xenomai upon detection of xenomai patched os (as of os_detection macro).
"setup_xenomai" means adding the correct folders for includes and the correct libraries for linkage (+call to xenomai-config)
real_time_tools (branch vberenz/xenomai) compiled ok on both non patched ubuntu 16.04 and patched ubuntu 14.04. 
Xenomai 2.6 only
=> added setup_xenomai.cmake

cmake/pkg-config.cmake
- add macros to find packages with pkg-config and export them in the catkin environment
- I used it in a package: git@git-amd.tuebingen.mpg.de:robotics/reactive_planners
=> Catkin and pkg-config

doc/clang_format.md, python/mpi_cmake_modules/_clang-format, python/mpi_cmake_modules/clang_format.py, resources/_clang-format, scripts/clang_format, setup.py
clang_format was not working (at least for me) when relative paths were passed.
I upgraded it to accept either relative or absolute path. 
I also added more print outs (list of files that will be modified).
I used it to format several packages in my workspaces, using both relative and absolute paths.
=> relative paths supported for clang_format executable

cmake/xacro.cmake
Fix a xacro executing warning upon cmake usage
[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."
[//]: # "Explain how you tested your changes"
I used it on the new robot_properties_hermes I am creating, soon uploaded on github.com/machines-in-motion
=> fix a xacro warning problem

resources/sphinx/sphinx/conf.py.in
Napoleon is a Sphinx extension that provides support for Google- and
NumPy-Style docstrings.
By building the documentation for trifinger_simulation, which uses Google style docstrings (left is without, right with napoleon):
=> Add napoleon to sphinx configuration

cmake/os_detection.cmake
[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."
My version of preempt_rt patch (5.4.59-rt36) has the output of `uname -a` match `PREEMPT_RT`, which fails the regex check.
[//]: # "Explain how you tested your changes"
Compilation proceeds using this simple modification, and does not otherwise.
=> Update preempt_rt regex

cmake/install_scripts.cmake
This is a replacement for `install(PROGRAMS ...)` which removes file
extensions from the given files.
Usage example:
install_scripts(
scripts/foo.py
scripts/bar.sh
DESTINATION lib/${PROJECT_NAME}
)
By using it to install the scripts of trifinger_cameras.
=> Add function "install_scripts"

cmake/get_python_install_dir.cmake, scripts/mpi_cmake_format, scripts/mpi_code_format, scripts/mpi_cpp_format, scripts/mpi_python_format
I had problems using the `mpi_*_format` commands because they get installed for Python 2 but the ROS 2 workspace sets everything up for Python 3.
This PR changes the formatting scripts to all run in Python 3.
Regarding finding Python in CMake: `get_python_interpreter()` apparently finds Python 2, so I replaced it with `find_package(Python)` which prefers Python 3 if both are present.
Please let me know in case it still needs to work with Python 2 somewhere, then we need to find another solution.
By running the `mpi_*_format` scripts in my workspace.
=> Use Python 3 for the code formatter scripts

cmake/os_detection.cmake
For a normal build (`colcon build`), this should not change anything
(i.e. OS gets auto-detected).  However, it is now possible to specify
the target OS at build time for cross compilation:
colcon build --cmake-args -DOS_VERSION=preempt-rt
What is a bit annoying with this solution is that for each package not directly using `OS_VERSION` (which is almost every package), cmake prints a warning:
> CMake Warning:
>  Manually-specified variables were not used by the project:
>    OS_VERSION
Is there maybe a better way to pass this argument?
By creating two singularity images on my non-real-time PC, one with a normal build and one with setting `OS_VERSION=preempt-rt`.  Then running both on the TriFinger robot.
- As expected, the normal build prints a "this is not going to run in real time" …
=> Allow specifying target OS by setting OS_VERSION

resources/_clang-format
Explicitly tell clang-format to preserve include blocks when sorting
includes.  For example
#include <a.h>
#include <c.h>
#include <b.h>
should not be not changed.  Without this setting the two blocks are
merged into one in newer clang versions:
#include <a.h>
#include <b.h>
#include <c.h>
Note: It seems that the default behaviour of clang-format changed.  It
was okay without this using version 6 but is needed with version 9.
Formatting code with clang-format-6 and with clangd-9 (which I assume corresponds to using clang-format-9)
=> clang-format: Preserve include blocks

cmake/sphinx.cmake, python/mpi_cmake_modules/documentation_builder.py
If no README.md is found, check if there is a README.rst.  Fortunately,
the documentation build already supports both independent of the file
extension, so the build works in both cases.
If both md and rst are there, md is used.
By building documentation for both cases.
=> Allow README.rst as alternative to README.md

resources/sphinx/sphinx/index.rst.in
Listing index.rst in a toctree inside itself results in build warnings
and a messed up navigation bar where everything appears twice.
Listing index.rst in a toctree inside itself results in the following build warnings:
.../index.rst: WARNING: self referenced toctree found. Ignored.
.../index.rst: WARNING: circular toctree references detected, ignoring: index <- index
After removing it, the warnings are gone and also the messed up navigation menu (where everything appears twice) is fixed now.  Left is before, right after:
Building the docs of trifinger_object_tracking (see screenshot above).
[//]: # …
=> fix (sphinx): Do not list index.rst inside itself

cmake/sphinx.cmake, pyproject.toml, python/mpi_cmake_modules/documentation_builder.py, resources/sphinx/sphinx/conf.py.in, scripts/mpi_doc_build
Point to the install location of the Python package instead of the source location in Sphinx' `conf.py` and when calling `sphinx-apidoc`. This way modules that are generated at build time (e.g. using pybind11) will be considered.
This fixes two related but distinct issues:
- `sphinx-apidoc` needs to use the install location, otherwise pybind11 modules will not be listed in the generated documentation.
- `sphinx-build` needs to use the install location (done through the change in `conf.py`) as otherwise the pybind11 modules will not be importable at build-time, resulting in even pure Python packages which import them internally to cause an error and thus to be excluded from the generated documentation.
WIP:
Before merging, the following points need to be considered:
By building the …
=> documentation build: Use Python package at install location in cmake build and improve Python doc builder

cmake/sphinx.cmake
It should check at the location that is actually used later to generate the doc.  This also makes it work for packages that do not store the Python code in `python/` (a convention from which I'm starting to deviate because it makes things easier for some editors if the Python package is found at the root of the repo).
By running it locally with robot_fingers.
=> fix: Check for Python at the PYTHON_PACKAGE_LOCATION

cmake/os_detection.cmake
Setting the same compilation flags for the low latency kernel and the rt-preempt kernel
Installed the low latency kernel and checked that indeed things were compiling accordingly. 
(note: after installation of the low latency kernel, 'uname -a' displayed something containing "lowlatency" without the need of extra configuration
=> os detection: lowlatency kernel treated as preempt-rt kernel

cmake/pybind11.cmake
This disables some linker optimisations in pybind11.  Normally one would not want to disable them but there are unresolved cases where the optimisation crashes GCC with an internal compiler error on some machines.
For now the easiest way to unblock this, is to disable the optimisation by setting `NO_EXTRAS`.
For reference, the error is
```
lto1: internal compiler error: in add_symbol_to_partition_1, at lto/lto-partition.c:153
0x7fbddc855082 __libc_start_main
../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: …
```
=> Add NO_EXTRAS option to add_pybind11_module()

cmake/sphinx.cmake
Only add the documentation target and its config if `GENERATE_DOCUMENTATION` is set.  Most importantly, this includes the check for the `bcat` executable, so the normal (non-documentation-)build will not fail anymore if breathing cat is not installed.
Resolves #51.
Built with and without `-DGENERATE_DOCUMENTATION=ON` and verified with prints that that the `find_program` part is only executed if needed.
=> Only add doc target if GENERATE_DOCUMENTATION=ON
